StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5E133960361D6C5D}" {
   Id "KOTH-ResumedText"
   Target_en_us "Based on the original Sa-Matra game mode"\
   "In general, King of the Hill has 3 teams/factions"\
   "- Blufor"\
   "- Opfor"\
   "- Indfor"\
   "To win the game, each faction must reach 100 points."\
   "To earn points for your faction, you must have the majority of players in the area of operations."\
   "If the same number of players are in the zone of operations, there will be no points gained until one team achieves the highest number."
   Target_fr_fr "Basé sur le mode de jeu original Sa-Matra"\
   "En général, King of the Hill se compose de 3 équipes/factions"\
   "- Blufor"\
   "- Opfor"\
   "- Indfor"\
   "Pour gagner la partie, chaque faction doit atteindre 100 points."\
   "Pour que votre faction gagne des points, vous devez avoir la majorité des joueurs dans la zone d'opérations."\
   "Si le même nombre de joueurs se trouve dans la zone d'opérations, il n'y aura pas de points gagnés jusqu'à ce qu'une équipe atteigne le nombre le plus élevé."
   Modified 1578321044
   Author "Arnaud"
   LastChanged "Arnaud"
  }
 }
}